<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SistemaEvaluacionAcademica.API</RootNamespace>
    <!-- Genera archivo XML con los comentarios /// para Swagger -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!-- Suprime warnings de propiedades sin documentar -->
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <!-- JWT: middleware de autenticación para ASP.NET Core -->
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <!-- La API conoce Application (servicios, DTOs) e Infrastructure (para DI) -->
    <ProjectReference Include="..\Application\SistemaEvaluacionAcademica.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\SistemaEvaluacionAcademica.Infrastructure.csproj" />
  </ItemGroup>

</Project>
